local assert = require('luassert')
local reply_input = require('nit.display.reply_input')

describe('nit.display.reply_input', function()
  describe('is_open', function()
    it('returns false when not open', function()
      assert.is_false(reply_input.is_open())
    end)
  end)

  describe('get_bufnr', function()
    it('returns nil when not open', function()
      assert.is_nil(reply_input.get_bufnr())
    end)
  end)

  describe('get_winid', function()
    it('returns nil when not open', function()
      assert.is_nil(reply_input.get_winid())
    end)
  end)

  describe('get_text', function()
    it('returns empty string when not open', function()
      assert.are.equal('', reply_input.get_text())
    end)
  end)

  describe('close', function()
    it('does not error when already closed', function()
      assert.has_no.errors(function()
        reply_input.close()
      end)
    end)
  end)

  describe('clear', function()
    it('does not error when not open', function()
      assert.has_no.errors(function()
        reply_input.clear()
      end)
    end)
  end)

  describe('set_text', function()
    it('does not error when not open', function()
      assert.has_no.errors(function()
        reply_input.set_text('some text')
      end)
    end)
  end)

  describe('map', function()
    it('does not error when not open', function()
      assert.has_no.errors(function()
        reply_input.map('n', '<C-s>', function() end, { noremap = true })
      end)
    end)
  end)
end)
