describe('nit.orchestration.versioning', function()
  local versioning = require('nit.orchestration.versioning')

  after_each(function()
    versioning.reset()
  end)

  describe('increment', function()
    it('returns 1 on first call for a thread', function()
      local version = versioning.increment('thread-1')
      assert.are.equal(1, version)
    end)

    it('returns incrementing values on successive calls', function()
      local v1 = versioning.increment('thread-1')
      local v2 = versioning.increment('thread-1')
      local v3 = versioning.increment('thread-1')
      assert.are.equal(1, v1)
      assert.are.equal(2, v2)
      assert.are.equal(3, v3)
    end)
  end)

  describe('get', function()
    it('returns 0 for unknown thread', function()
      local version = versioning.get('nonexistent')
      assert.are.equal(0, version)
    end)

    it('returns current version after increments', function()
      versioning.increment('thread-1')
      versioning.increment('thread-1')
      local version = versioning.get('thread-1')
      assert.are.equal(2, version)
    end)
  end)

  describe('is_current', function()
    it('returns true when version matches', function()
      versioning.increment('thread-1')
      local is_current = versioning.is_current('thread-1', 1)
      assert.is_true(is_current)
    end)

    it('returns false when version is stale', function()
      versioning.increment('thread-1')
      versioning.increment('thread-1')
      local is_current = versioning.is_current('thread-1', 1)
      assert.is_false(is_current)
    end)

    it('returns false for unknown thread with version > 0', function()
      local is_current = versioning.is_current('nonexistent', 1)
      assert.is_false(is_current)
    end)
  end)

  describe('independent threads', function()
    it('have independent counters', function()
      local v1_a = versioning.increment('thread-a')
      local v1_b = versioning.increment('thread-b')
      local v2_a = versioning.increment('thread-a')

      assert.are.equal(1, v1_a)
      assert.are.equal(1, v1_b)
      assert.are.equal(2, v2_a)

      assert.are.equal(2, versioning.get('thread-a'))
      assert.are.equal(1, versioning.get('thread-b'))
    end)
  end)

  describe('reset', function()
    it('clears all counters', function()
      versioning.increment('thread-1')
      versioning.increment('thread-2')
      versioning.reset()

      assert.are.equal(0, versioning.get('thread-1'))
      assert.are.equal(0, versioning.get('thread-2'))
    end)
  end)
end)
