name: Generate Docs

on:
  push:
    branches: [main]
    paths:
      - "README.md"

permissions:
  contents: write

jobs:
  docs:
    name: Generate vimdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: kdheepak/panvimdoc@662fb20304d20c539fb48a0bde628f5165507de7 # v4.0.1
        with:
          vimdoc: nit

      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "chore(docs): auto-generate vimdoc"
          file_pattern: "doc/*.txt"
